name: Firebase Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      deploy_functions:
        description: 'Deploy Firebase Functions'
        required: true
        default: true
        type: boolean
      deploy_firestore:
        description: 'Deploy Firestore rules and indexes'
        required: true
        default: true
        type: boolean

env:
  NODE_VERSION: '18'
  FIREBASE_PROJECT_ID: stage-pass-b1d9b

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Deploy Firestore rules and indexes
      if: ${{ github.event.inputs.deploy_firestore == 'true' }}
      run: firebase deploy --only firestore:rules,firestore:indexes --project ${{ env.FIREBASE_PROJECT_ID }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Deploy Firebase Functions
      if: ${{ github.event.inputs.deploy_functions == 'true' }}
      run: firebase deploy --only functions --project ${{ env.FIREBASE_PROJECT_ID }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Run health check
      run: |
        echo "Running health check..."
        curl -f https://us-central1-stage-pass-b1d9b.cloudfunctions.net/api/ || exit 1
        echo "Health check passed!"
        
    - name: Notify deployment success
      run: |
        echo "✅ Deployment to ${{ github.event.inputs.environment }} completed successfully!"
        echo "🌐 API URL: https://us-central1-stage-pass-b1d9b.cloudfunctions.net/api"
